#+TITLE: Truth, Inverted
#+TAGS: fiction

* Truth, Inverted

The ice chunks floating around them indicated the current temperature on the world of Mmrab'ii. This, of course, didn't bother anyone--they had not only grown up here themselves, but their species had evolved to thrive in this exact environment. A species with photosensitive cells, let alone fully developed eyes, might have commented on how dark it was, but those species didn't exist on Mmrab'ii. With no visible light to speak of, why would they? It would offer no evolutionary advantage.

Tentacle by tentacle Zphix and Jqi pulled themselves through the university's main thoroughfare. The aquatic world of the student and his teacher restricted their motion to a slow crawl as they continued their fierce repartee.

"--and the philosopher Yyxin has been ridiculed for centuries--since the ages of the Njok Dynasty--for his beliefs!" said Jqi.

"I don't want the same fate as Yyxin, but there's something so honest about his theories," said Zphix. "What if he was right? Why are we so sure our planet is a sphere? We have nothing but circumstantial evidence. If it is a curved world, it must be subtle. And with such subtlety, we could be misinterpreting the situation."

Jqi laughed, which for the squid-like creature looked like a balloon inflating and deflating. "You're not the first to be put off by these things. I doubted them too in my younger days, but this is not a conspiracy theory, there's no one who's intentionally hiding the truth. Since the dawn of history, our species has been looking for its origins and trying to uncover the answers. Our theories are the most logical that fit the evidence we have. But science cannot be taught, it must be understood through experimentation," he paused for a moment, reading Zphix's oblong face for a sign of understanding, then continued, "here's a thought experiment that might be of help to you: imagine you were to pick a direction, any direction, and crawl in a straight line in that direction. Do you know where you would eventually end up?"

"I suppose I would /eventually/ end up where I started--at least according to the textbooks. Though, that would also be true for a taurus--a cylinder bent so the two ends meet, or any shape that's homeomorphic to a sphere," said Zphix, recalling that last fact from a math textbook he had used for class.

"That is correct, Zphix," said Jqi, "But you realize, of course, that not only would you eventually reach your starting point regardless of the direction you started crawling, but also that you would cover roughly the same distance regardless of the straight line path you chose. That can only be the case for one shape."

"Yeah, I guess. It would have to be a sphere, or close to it," said Zphix, conceding this point.

"Right again!" said Jqi, showing the beaming smile of a teacher who had finally broken through with a student.

"That all makes sense, but if that is the case, then if someone were to swim away from the surface, they should get farther and farther away from the planet until eventually they might even leave the water altogether, right? But that is not what has happened when it's been attempted."

"All true, but this is due to flaws in the experiment. Traveling in the upper aquasphere is dangerous and difficult. The turbulent currents make it a challenge to control one's direction, and one might easily be turned upside-down without even realizing it. This is why all attempts have ended with the swimmer returning to the surface. Although--sometimes, /unusually/ far from where they started. It will be difficult to design an accurate test for this theory, due to limits in our physiology."

"Ok then, that implies that if one were to dig down into the ice, instead of going up, they would eventually come out the other side--if the world is a sphere, that is."

"You have the correct model in your head, but going down is just as difficult as going up. We haven't been able to reach a sufficient depth to confirm or deny the theory. As far as we've been able to go, it's been solid ice with a few rocks splayed throughout. But remember, this is just one experiment. The others we have discussed build a much stronger case."

Zphix could only muster up an "Okay." He now understood the constraints of the situation, and was satisfied with the conclusions that had been drawn.

-----------------------------------------------------

Mission commander, Dr. Isaac Perilean, and his crew had tuned their galactic translators and pressed them to the surface of Europa--the ice-coated moon of Jupiter. This was humankind's first manned trip to the Jovian moon. It had been been well established in recent flyby missions that life flourishing under the thick icy surface was a near certainty. Of course, life had already been discovered on other worlds, so this was not a world-shattering breakthrough, just an effort to increase the knowledge of humankind. Dr. Perilean and his team of biologists, physicists, and anthropologists (like himself), had been sent to learn as much as they could about the wild species.

Through the output of their translators, they listened to the conversation, between the two aliens, taking place below them--physically separated from it by only 100 kilometers of ice, but given what they had just heard, they could not have felt further.

From the icy crust of Europa, which surrounded a liquid water core, the scientists sensitive instruments detected vibrations consistent with light scraping of ice. It's implications were unmistakable: the species below did not make their civilization on the /outer/ surface of a sphere as their conversation had indicated, but rather the /inner/ surface. This species was, of course, blind to this because they were--well--blind. Ice may be transparent in small amounts, but at a depth of 100 kilometers, it about as transparent as a concrete wall. The species had evolved without eyes, and created a civilization on the precipice of the black abyss of Europa's subterranean ocean.

The Europans were living on an inverted plane of existence--and they lacked the senses required to notice. They were trapped in an anomaly, limited by their physiology and the senses they were given to understand the world with.

Dr. Perilean stumbled backwards in catatonic disbelief. His feeling of superiority over the small aliens quickly dissipated as it gave way to fear. Fear of being fooled by one's own senses--a massive, species-wide delusion.

And so the thought remained: /if them, why not us?/
