* Truth, Inverted

The ice chunks floating around them indicated the current temperature on the world of Mmrab'ii. This, of course, didn't bother anyone--they had not only grown up here themselves, but their species had evolved to thrive in this exact environment. A species with photosensitive cells, let alone fully developed eyes, might have commented on how dark it was, but those species didn't exist on Mmrab'ii. With no visible light to speak of, why would they? It would offer no evolutionary advantage.

Tentacle by tentacle Zphix and Jqi pulled themselves through the university's main thoroughfare. The aquatic world of the student and his teacher restricted their motion to a slow crawl as they continued their fierce repartee.

"--and the philosopher Yyxin has been ridiculed for centuries--since the ages of the Njok Dynasty--for his beliefs!" said Jqi.

"I don't want the same fate as Yyxin, but there's something so honest about his theories," said Zphix. "What if he was right? Why are we so sure our planet is a sphere? We have nothing but circumstantial evidence. If it is a curved world, it must be subtle. And with such subtlety, we could be misinterpreting the situation."

Jqi laughed, which for the squid-like creature looked like a balloon inflating and deflating. "You're not the first to be put off by these things. I doubted them too in my younger days, but this is not a conspiracy theory, there's no one who's intentionally hiding the truth. Since the dawn of history, our species has been looking for its origins and trying to uncover the answers. Our theories are the most logical that fit the evidence we have. But science cannot be taught, it must be understood through experimentation," he paused for a moment, reading Zphix's oblong face for a sign of understanding, then continued, "here's a thought experiment that might be of help to you: imagine you were to pick a direction, any direction, and crawl in a straight line in that direction. Do you know where you would eventually end up?"

"I suppose I would /eventually/ end up where I started--at least according to the textbooks. Though, that would also be true for a taurus--a cylinder bent so the two ends meet, or any shape that's homeomorphic to a sphere," said Zphix, recalling that last fact from a math textbook he had used for class.

"That is correct, Zphix," said Jqi, "But you realize, of course, that not only would you eventually reach your starting point regardless of the direction you started crawling, but also that you would cover roughly the same distance regardless of the straight line path you chose. That can only be the case for one shape."

"Yeah, I guess. It would have to be a sphere, or close to it," said Zphix, conceding this point.

"Right again!" said Jqi, showing the beaming smile of a teacher who had finally broken through with a student.

"That all makes sense, but if that is the case, then if someone were to swim away from the surface, they should get farther and farther away from the planet until eventually they might even leave the water altogether, right? But that is not what has happened when it's been attempted."

"All true, but this is due to flaws in the experiment. Traveling in the upper aquasphere is dangerous and difficult. The turbulent currents make it a challenge to control one's direction, and one might easily be turned upside-down without even realizing it. This is why all attempts have ended with the swimmer returning to the surface. Although--sometimes, /unusually/ far from where they started. It will be difficult to design an accurate test for this theory, due to limits in our physiology."

"Ok then, that implies that if one were to dig down into the ice, instead of going up, they would eventually come out the other side--if the world is a sphere, that is."

"You have the correct model in your head, but going down is just as difficult as going up. We haven't been able to reach a sufficient depth to confirm or deny the theory. As far as we've been able to go, it's been solid ice with a few rocks splayed throughout. But remember, this is just one experiment. The others we have discussed build a much stronger case."

Zphix could only muster up an "Okay." He now understood the constraints of the situation, and was satisfied with the conclusions that had been drawn.

-----------------------------------------------------

Mission commander, Dr. Isaac Perilean, and his crew had tuned their galactic translators and pressed them to the surface of Europa--the ice-coated moon of Jupiter. This was humankind's first manned trip to the Jovian moon. It had been been well established in recent flyby missions that life flourishing under the thick icy surface was a near certainty. Of course, life had already been discovered on other worlds, so this was not a world-shattering breakthrough, just an effort to increase the knowledge of humankind. Dr. Perilean and his team of biologists, physicists, and anthropologists (like himself), had been sent to learn as much as they could about the wild species.

Through the output of their translators, they listened to the conversation, between the two aliens, taking place below them--physically separated from it by only 100 kilometers of ice, but given what they had just heard, they could not have felt further.

From the icy crust of Europa, which surrounded a liquid water core, the scientists sensitive instruments detected vibrations consistent with light scraping of ice. It's implications were unmistakable: the species below did not make their civilization on the /outer/ surface of a sphere as their conversation had indicated, but rather the /inner/ surface. This species was, of course, blind to this because they were--well--blind. Ice may be transparent in small amounts, but at a depth of 100 kilometers, it about as transparent as a concrete wall. The species had evolved without eyes, and created a civilization on the precipice of the black abyss of Europa's subterranean ocean.

The Europans were living on an inverted plane of existence--and they lacked the senses required to notice. They were trapped in an anomaly, limited by their physiology and the senses they were given to understand the world with.

Dr. Perilean stumbled backwards in catatonic disbelief. His feeling of superiority over the small aliens quickly dissipated as it gave way to fear. Fear of being fooled by one's own senses--a massive, species-wide delusion.

And so the thought remained: /if them, why not us?/















Tentacle by tentacle Zphix and Jqi pulled themselves slowly through the university's main thoroughfare. Slowly is all but a requirement for the tentacled creatures in the aquatic world of the student and his teacher. They continued on while engaged in fierce repartee.


"And can you tell me what shape that must be?"

"



 You don't want to end up like him, do you?





What if the creatures below were not the only ones who could be deceived by their senses?

If the creatures below could be so fooled by their senses, couldn't humans?






* mention why it is dark

"A good theory. And, in fact, it has been tested numerous times. The results, however, remain inconclusive.
It seems that no one has been able to reach a high enough velocity to escape the pull of the planet. We believe this is the case, because after generating some distance from the surface, all have have been unsuccessful at fighting through the the whirling currents of the upper aquasphere. shortly after trying, all have found themselves back on the ground--though sometimes, /unusually/ far from where they started. It is unlikely that we will ever be able to accurately test this theory, as our species lacks the swimming power to get past nature's furious currents."

"That all makes sense I guess, but suppose one were to swim away from the surface? Wouldn't they get farther and farther away from the planet, and eventually leave the water altogether?"

Zphix and Jqi continued their snail-like crawl across the icy ground--clinging to it with their spiked tentacles--engaged in the pedantic reparte so common amongst academics.

"Okay, I think I get it now," said Zphix with a childlike sulk,	"all the evidence really does point to us living on a sphere."

That would make you a brave swimmer indeed. Many have tried, but

# "Well, it would be quite a long walk, could be treacherous too, but

# , that be the case for any direction you choose, but you would cover approximately the same distance in each possible direction before returning to your starting point?"


They had heard the words of the alien professor and his student, and they sat they in disbelief.

Through 100 kilometers of solid ice, they listened to the conversation between Zphix and Jqi. They felt a sense of pity--for the Europans had such a poor understanding of the universe, simply because of where they were. Trapped in an anomaly. Ice may be transparent in small amounts, but under 100 kilometers of ice, it's as opaque as a concrete wall. That means that species must have evolved, without eyes, in the black abyss that is the subterranean ocean of Europa. They would likely have no sensitivity to temperature, because there is so little variance within the ocean, there would be no reason for that kind of sensitivity to evolve.


* get at, but don't straight up ask the question: how do we know we're not in some kind of bubble like the Europans?




"You should never trust them! Not blindly anyway. I encourage you to try this experiment. It might even be worth taking a semester off of school for. I've done it myself, and it is a powerful experience. But for a moment, let's just assume you trust me. /If/ what I say is true, and /if/ "




 and it's the common knowledge that's wrong? What if the creation stories, and the Great Below, and /all of it/ is a lie--or even a misunderstanding? These stories have been passed down for generations, but where do they even come from?"




possiblilities:
- what happens if they go up?
- what happens if they go down into the ice?
- explain great below?




























"Well, I haven't asked a mathematician myself, but I suppose they would."





"Woah! Slow down for a second," said Jqi. "You're getting worked up now. Let's work through this. If you were to pick a direction and walk in a straight line, would you at some point reach the point you started from?"

"Yes, I suppose."

"And wouldn't that be the case for any direction you could possibly choose?"

"Well, yes but--"

"And wouldn't /any/ mathematician worth their weight in ice tell you that the only three dimensional shape for which that holds true is the sphere?" said Jqi with growing confidence.

"That's all true, Jqi, but I'm still not convinced.  what if instead of walking /along/ the ice, you instead went upwards, /away/ from the ice?"

Jqi could sense that Zphix


, feeling his momentum fading.


You need to remember that not all proof lies in the existence of supporting evidence, but also in the non-existence of contrarian evidence. All experiments that make an effort "



"Of course the universe is finite, you idiot," said Jqi "you must've been to every corner of it yourself. Haven't you?"

"I have, I suppose. But something still--it just leaves so many questions unanswered."

"Small? It would take you /weeks/ to get all the way around it!"

"It would, but there are so many unanswered questions! Like: what /is/ the Great Below? And, if the priests are right, we are the only sentient species in the universe. What are the odds of that?"

"

"Yes, but it must have come from /somewhere/, where did it come from Jqi?"

"You've heard the stories--it came from Gylaia. Goddess of the Essence. She formed the ground from the sky, and said 'Let there be motion!' and there was. It was just the smooth flowing of the ether from there. Later, the minerals in the ground began to disolve, and slowly formed the building blocks of... well, us!"

"I have heard the stories, just... all I'm saying is /what if/ we're missing something?" said Zphix, feeling a little silly at this point. Had he gone too far? Was he just questioning why up was up and down was down?

Jqi felt none of the same doubts as Zphix. /The world appeared so simple--what reason would there be for disrupting the status quo/? Science class had been quite clear growing up; so rote in its repetitive simplicity, he could still picture his teacher talking: /We are pushed to the ground by the round spirits/. Hard to argue with that logic. Plus there was no experimental evidence refuting it. When someone would die, the round spirits would leave the body and wander the surface, before disappearing into the ground; the body would then drift away--into the sky.





-------------------------------------------------------




















They lived unassuming lives, mostly adhering to the admonishments of the Godess of the Ocean--she lived down the street. Gylaia









* Europa; human and europan

Ambassidor Zphix Arctizoa made a sound.

Isaac nodded dutifully after a moment's delay--the translator built into his helmet lagged the realtime conversation by a second or so. It also took Isaac a moment to comprehend the point. The ambassidor's comment on the pleasant weather had been lost on Isaac, his notions of /pleasant/ weather varied greatly from those of Isaac's home planet.

From Isaac's perspective, when someone talks about nice weather, they're considering the temperature, wind speed, maybe the warmth of the sun peaking through some fluffy, white clouds. Ambassidor Arctizoa meant none of those things. On Europa--the smallest of Jupiter's moons--none of those things really mattered--or existed. The temperature hardly varies more than a few degrees centigrade between the coldest and warmest parts of the occupied moon. Wind and clouds are not a factor either, seeing as Europa has no atmosphere--well, that, and the native species lives in intricate mazes of subterranean ice caves, carved from the inside of the planet outwards.

"I spent spent three years doing research in Antarctica--hardly noticed the the cold," said Isaac with a wry smile. The ambassidor laughed hartily, which for the subterranean ocean-dwelling Europans looked like a balloon repeatedly inflating and deflating.

"This is the warm season on Europa, Doctor," said the ambassidor, "perhaps I can offer you a blanket before we begin." This was, of course, a joke. Europa had no seasons, because almost none of the moon's heat came from the sun. It was generated mostly from the friction of tidal forces--Jupiter's massive gravitation expanding and compressing the planet with each revolution. Also, wearing a blanket over his pressurized suit would have been pointless for obvious reasons.

Isaac and the ambassidor continued moving forward along the Europan thoroughfare. Society on Europa is, of course, vertically inverted. Europa is like a giant truffle floating through space--a truffle filled with liquid water instead of caramel, and coated with a layer--100 kilometers thick--of ice instead of delicate chocolate. With the warmest parts of the subterranean ocean being near the surface, that is where the highest density of species can be found.

* explain how shit is upside down; something happens where isaac gets lost or some shit

The Europans had evolved, in their entirety, within the confines of this celestial dessert. This evolution occurred against all odds. Despite there being liquid water, it was still only a few degrees above freezing. And despite its transparency in moderate amounts, at a depth of 100 kilometers, the shell of ice is totally opaque. An endless ocean lies dormant. An abyss dark enough to inspire blackness itself. The Europans had built their entire society on the underbelly of something akin to an underground lake.








Isaac returned the comment with a superficial smile, knowing that any display of weakness could hurt negotiations. But it was all for show--he was very cold. Fortunately, the ambassidor could not detect his shivering under the suit, and the quiver in his voice was masked by the translating device in his helmet. He knew he could turn up the heat in his suit, but it ran on a battery and he was unsure of how long he would be away from base camp back on the surface. It would be okay, he thought, /I'll be back soon/.

For now, Isaac would have to be patient, and let the negotiations take their course. But there was a great deal on the line, especially for Isaac.

"Thank you for inviting me into your home, Mr. Ambassidor," said Isaac, "but I don't suppose you have a larger entrance--one that's a little more... uh... human-sized?".

"Oh dear, as you might expect, these entrance tunnels were built before we even knew such large biological beings existed. Perhaps you'll be able to just squeeze in now, and I'll make sure to have some alterations done for the future."

Isaac squeezed in. His facial expression told the complete story of how he felt about cramming his body, and his expensive, government issued space suit through what was only slightly larger than a cat door. Of course, Ambassidor Arctizoa wouldn't be able to interpret human facial expressions, that skill is reserved for human instinct.

"Doctor Perilean, I--"

"Please, call me Isaac"

"Isaac, then, I apologize for such an unusual setup for our negotiations."

The main chamber of the ambassidor's abode, was clearly designed for the orientation in which the native Europans spend their time. Europa is a giant ball of liquid water encased in a thick--like, 100 kilometers thick--layer of ice. So, with the liquid water on the inside and the solid surface on the outer edges, this dominant Europan species (of which Ambassidor Arctizoa was a member) evolved almost as the exact inverse of Earth's bottom-dwellers. They are quite literally /top-dwellers/. Their spiked, many tentacled appendages serve the purpose of holding them to the upper ice. So, when Isaac stood up in the chamber, as a human would stand up--away from the direction of gravity--him and the ambassador, who was hanging from the ceiling, were face to face, but upside down!







All Europan structures have their entranceways on the ocean-side of the moon's icy crust. So, to get to it, Isaac first had to travel down the massive 100 kilometer deep hole, to the subterranean ocean.

Their discussion continued inside the Zphix's home--a particular ice cove about 27 kilometers below the surface, and completely filled with water--

Isaac Ides had spent his short career as researcher of extraterrestrial anthropology for NASA. For all of the groundbreaking work he had published, he was still derided by fellow academics. Some personality types are just harder for the Old Boys Clubs of academia to accept. There was no topic that was taboo for Isaac, despite what the anthropology community thought. Despite his numerous accalades and early reknown for out-of-the-box thinking, he was disliked by many of his peers who followed more traditional paths.

Isaac found himself trying to recover

* 600

* problems
I don't understand wtf Zphix is. If he's too primitive, then there can't be any intelligent conversation with him, where he teaches about how Europa works. If he's too intelligent, it's grossly unrealistic.
** Solution?
What if Zphix is an intelligent species? How would evolution have led their species to that point? If there was an intelligent species so close, why didn't we notice them? Intelligence on Earth evolved on land, but maybe it could've happened under water on Europa which is also 4 billion years old, and hasn't suffered the same kinds of extinction level events as Earth, maybe?







Isaac Perilean, PhD, had found himself in a rough patch with regards to the scientific community. His methods were occassionally described as unethical. He never quite understood why. After all, he had never done anything to endanger a /human/. Seeing as humans were rapidly establishing themselves as the conquerors of the galaxy, it was clear to him that their needs and wants fell above those of other species. Doing the greatest good for the greatest number of beings would have to favor the species with the /most/ beings.

Isaac's malfeasance cause the Earthan Senate's Committee for Planetary Science to insist that he be restationed. But being restationed was not always a bad thing. Some planets have breathable atmospheres, and fall well within the habitable zone of their star, contributing to comfortable conditions for humans. Europa was not one of those places. Isaac often remembered the ancient legend of Napolean, the dictator banished to the island of Elba. Isaac's favorite part of Napolean's story was not that he conquered Europe, but that he escaped from Elba. This was, however, only a rough analogy of the position Isaac found himself in. Isaac was not in exile. He could go back to his home on Earth anytime he wanted. He just couldn't practice science there. But just as Napolean was, in his own heart, an /emperor/, Isaac was a /scientist/.

Despite the unsavory turn of events, Isaac was still grateful to /only/ receive a slap on the wrist. The clemency he received was largely due to the influence his uncle was able to apply as a former senator. There was also a prime opportunity for redemption. The native, dominant species on Europa was had begun a series of targeted attacks on the human surface-dwellers. There was little doubt that these attacks were planned, and there was even less doubt as to why.

* The Incident

Way back, early in the second millenium, Earth scientists had speculated (for centuries!) that Europa might contain life. This because Europa had been know for some time to be, basically, a giant truffle floating through space--a truffle filled with liquid water instead of caramel, and coated with a layer--100 kilometers thick--of ice instead of delicate chocolate. The Europans had evolved, in their entirety, within the confines of this celestial dessert. This evolution occurred against all odds. Despite there being liquid water, it was still only a few degrees above freezing. And despite its transparency in moderate amounts, at a depth of 100 kilometers, the shell of ice is totally opaque. An endless ocean lies dormant. An abyss dark enough to inspire blackness itself.

Earth scientists been studying Europa, from the surface, for decades now. Getting below the surface proved difficult though. Drilling, even on Earth, is a difficult problem. Contrary to the major advances in space travel, traveling straight down, towards the Earth's core, remained an intractable problem. The most advanced drilling apparatuses were still only capable of going a few short kilometers below the surface. There are some obvious advantages to drilling on Europa, however. For one, it is coated in ice, which is usually easier to drill through. The down side is that as you drill, the tiny ice flakes that get chipped away are warmed by the drill, and quickly turn into water. So, as you drill, the hole, instead of being filled with ice, becomes filled with water. Which in the sub-arctic temperatures of the Europan surface, quickly turns back to ice. To make a hole that doesn't continually close itself up, an aparatus is needed to keep the water above freezing while pumping it up to the surface. This is basically a giant heated straw, stretched at least 100 kilometers in length. The logistics /alone/ of using one of these straws is enough to deter any sane person. But the scientists on Europa were desperate.

The Endeavor Project, with the goal of exploratory drilling, began one fine day, just after the faint sun rose above the flat, Europan horizon. It was largely uneventful--the constant humming of the drill was felt at the base camp, nearly 4 kilometers away. The scientists didn't mind though--it was a break from the eerie silence that normally plague's the desolate planet.

About 7 weeks after drilling began, Europa was changed forever.

The telemetry systems of Endeavor went offline. This was followed a few seconds later by a persistent rumble, much stronger than the expected hum of the drill.

Europa, the water balloon of our solar system, is under immense pressure. At least at certain times. The /net/ pressure under the ice is zero, so for a point whose pressure decreases due to the tidal effects, there is another point whose pressure increases by the same magnitude.	The high pressure can cause cracks in the entire shell, leading to great floods that wipe any sign of crater inpacts from the surface. Such ruptures only occur every few million years. More frequently, they cause small cracks that have no effect far below that surface.

Endeavor hit one of those cracks.

The instant pressure release caused plumes of water to shoot back up the hole like hydrolic jets at nearly 500 meters per second, quickly wreaking havoc on the Endevour drill in the process. After about 10 seconds, the now derelict drill, along with over 100 kilotons of liquid water exploded into the sky. It quickly froze and came down again in the the form of snow. Except the drill, which came down in the form of a broken drill.

The internal pressure of Europa quickly reached equilibrium after the breach.

But snow and a broken drill were not the only precipitants of the cryo-geyser.

* The Europans

Humans had come to learn that most extraterrestrial species are small and closely related to bacteria. But these were no bacteria--about the size of small house cats. Translucent skin and dozens tentacles. The tentacles were spiked, making the species look as if a porcupine, a centipede, and an octopus had mated.

By the time the scientists on site had an opportunity to look at them, they were dead. It was clear to see that the low temperature and pressure had not treated them kindly.

Despite the overbearing deadness of the uncovered beings. This discovery was monumental in that it was the first encounter with extraterrestrials /within our own solar system/. The scientists on Earth would laud this breakthrough like few others.

-------

Meanwhile, deep below the surface. There was mayhem. Zphix was with his family, enjoying a heaping serving of his favorite algea.



* 1486; tomorrow, write down thoughts as soon as they come into my head. it doesn't matter how stupid it is


Zphix (this is the anglicized spelling, which is almost entirely arbitrary, as English has none of the same phonemes as Zphix's native tongue--no Earth languages do...) spent his youth bouncing between much smaller ice caves like these. Such nomadic tactics are common on the stalagmite ridden, and oft shifting landscape of Europa. In fact, until developing sufficient technology, this was how /all/ primeval Europans lived. But by the current Europan date, 65434028 S.R., such a lifestyle is uncommon--minus a few /uncivilized/ tribes. Most Europans--or as they call themselves: MMbura'ii, lived in proto-cities--dense collections of subterranean igloos, connected by intricate networks of tunnels spanning various depths.

The talk between Isaac and Zphix was surprisingly small considering that this was a monumental meeting--one in which the terms of the relationship between Earthans and Eupopans would be hammered out.



There had been a growing tension over the past two centuries. Scientists from Earth had set up base camps on the Europan outer surface


Zphix had taken a long time to begin trusting humans. His primitive species could be equated to the hunter-gather tribes that we, humans, descended from. So, his inviting Isaac into his home was not to be taken lightly.


But life is adaptable. When the selection biases are shifted towards the cold and the dark, life makes due. Life started on Europa the same way it did on Earth. Simple molecules formed amino acids, gradually snowballing into larger structures, and occasionally, taking on a self-replicating form. From there the replication continued, and with the help of minor mutations--species were born.

The current dominating species, the /caeruleus palmea/, Hands for short, make their lives on the inner surface. From the perspective an an Earthian, they have evolved and lived on an inverted plane of existence. To them, /up/ is quite literally /down/. A hand, so named for it's disproportionately large, many pronged appendages, makes it's life burrowed within the inner surface.

The structures built by the hands, while grandiose homes to the locals, might still be considered no more than ice caves on Earth. These caves are essentially extruded out of the ice--as if an igloo was carved into a mountain of ice cream. That's not meant to detract at all from these magnificent structures--an archaeologist would have a heyday exploring even a modest one. In fact, for their fantastic structure, Dr. Hemming Bodwith coined the term /supergloo/, with the obvious implication of complexity versus the archaic /igloo/.

The entrance of a supergloo, from the surface, looks like a big hole--about 1 meter in diameter. Upon closer inspection, it becomes clear that it is not carved straight down, but at a steep angle with the vertical. To climb in, there are well defined notches on the inner rim of the hole, which can be grabbed or simply pressed against with your hands like a wedge, as you descend (upwards) into the hole. It's like inching up a chimney. Once fully emersed in the hole, the path takes a sharp turn--like a zig-zag--in nearly the opposite direction. The purpose of which is to shield the inner cavern from the tumult of the weather outside. But it does pose a challege for humans--which are about 3 times bigger than the average full-grown hand. Once past this maze, there is more than sufficient room to stand. There are many more rooms in this tomb-like, subterranian structure.

A species whose complexity is dwarfed by our own, the hands have managed to form an ornate system of branching tunnels that connect many of their personal supergloos. The intricate networks form proto-cities.

They are able to do most of their building using two simplistic techniques. The earliest known and simplest technique is to rapidly rub their gangly appendages against the icy shell of the planet. The heat generated is enough to melt away some of the ice. This allows for very fine control, but is a slow process, and can take weeks to burrow even a moderate hole. This method would be far less effective for humans, who would quickly develop frostbite or hypothermia. The Europan hands, however, have evolved under these acutely frigid conditions and are not susceptible to such maladies. Hands have actually evolved to have very small scales on their finger-like appendages. These appear to be useful for creating more friction, and thus melting the ice faster.

* start here tomorrow; get out of metaproblem space



"Nice? I'm freezing down to my bones!" said Isaac, "I haven't seen the sun in weeks."

"Pays to be cold-blooded--am I right or am I right?"



* scratch
** story in three parts, all are scientific journals. 1st is some point in time when the hands are primitive, second is later time when they are much more complex

Since his younger days Zphix has had a knack for sensing other beings in the area. This is an ability taken for granted by Earth inhabitants, because we live our lives basked in sunlight. But no such luxuries exist for the Europans. This ability of Zphix's simplified his decision to pursue hunting as a career. Though, it really is fortunate that has such a natural skill--most do not. Also, even if he had no skill at all, there is only one other Europan profession: the builder. Building has a different


Despite ascending to the societal stage of an organized civilization so long ago, the Europan citizens are trapped in what is similar to the Earth people's Stone Age. This is largly due to the lack of diverse resources, and the unreactive environment. On Earth, the Stone Age ended, in part, because humans learned to use fire and heat to design bronze tools. That is for all intents and purposes, impossible for the tragic Europans. It's impossible, because the great Europan Empire is entirely under water.

The Europan ocean is teeming with life, most of which

"Nice out today. Eh, bud?", said Zphix.

For a Europan, Zphix was living the idyllic life.

Water can be pumped out without a problem /to a certain extent/, but it is quite difficult to pump out water from 10 or more kilometers deep hole like a giant straw. The vaccuum power alone would need to be tremendous! And then there's the displaced water. A hole 1 meter in diameter, and 10 kilometers deep would need to have 10,000 metric tons of water taken out and placed somewhere else. In practice, the weight wouldn't be so bad, because the gravity on Europa is about 13% of Earths, but it's not easy to find somewhere to put a huge volume of liquid on a moon with an almost featureless surface. A series of damns and streams would need to be engineered to allow the water to flow somewhere, but in digging those, you would be creating more water to deal with. The only solution would be to do it slow enough that the water would have time to freeze once it had been moved out of the way. Though, that wouldn't take much time considering Europa's surface temperature--cold enough to kill a human in seconds--that is, if the low pressure didn't do it first.

* thoughts
- it's convenient to stay near the shell, to maintain your orientation, but it's not required. of course, if you were to drift away from the surface, you might risk becoming disoriented in the featureless blackness.
- scientists have no idea how old europa is, because of it's ageless surface
- S.R. means Since Rupture. implying there was a great rupture in the surface at some point in the past.
- days are tracked by cracks/deformations in an agreed upon location. sort of like GMT.
- how do they build things?
- why are they near the surface? as opposed to living like fish below?
- what is their view of the universe like?

** my questions to myself
- who is the narrator?
- is he a character in the story--the earthman?
- maybe the narrator should be a third-person earthman? and there is some other earthman involved in the story?

* Premise
3rd person narrator
An earthman is exploring the subterranian civilization of europa

The exact location on the planet is difficult to describe. See, the moon of Jupiter that we call Europa is a ball of mostly water, floating through space. Space is cold, so the outside of Europa is solid ice--about 100 kilometers of it. That may seem thick--and it is--but on the grand scale of planets and celestial objects, 100 kilometers is quite thin. Zphix's home world has about the structural integrity of one of those truffles of liquid carmel coated by a thin layer of chocolate. Squeeze too hard, and some of the inner goo might shortly find itself as outer goo. And squeezing is exactly what Jupiter does. Jupiter, being an uncomfortably massive ball of gas, tugs on Europa. This is, of course, what keeps it in orbit, but it does more than that, it deforms the


, speaking to Jqi
